### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by kubamarkiewicz** [mcharytoniuk/octobercms-headless#2]
Hi, I am trying to use your plugin, however I can not make it work ... I have created and configured new plugin following the instructions, but when I go to update page the from stays blank, the fields do not appear ... it does not give any errors neither. Could you provide an example of a working plugin?

**Comment by mcharytoniuk** [comment]
@kubamarkiewicz sure, I'll take a look this week and get back to you.

**Comment by mcharytoniuk** [comment]
@kubamarkiewicz also, sorry for the 4 day late response, I did not notice the notification. If you need some quick support, you can reach me out via email: mateusz.charytoniuk@newride.tech

**Comment by mcharytoniuk** [comment]
@kubamarkiewicz sorry for the huge delay. This is the repo with the complete working example:
https://github.com/mcharytoniuk/octobercms-headless-example

**Comment by kubamarkiewicz** [comment]
Thank you for providing an example, I will try it.
